config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'interests/new'
  end

  namespace :admin do
  get 'interests/edit'
  end

  namespace :admin do
  get 'interests/index'
  end

  get 'sessions/new'

   namespace :admin do
    resources :users, :individuals, :organisations, :opportunities, :applications,
    :posters, :searches, :applications, :skills, :classifications, :districts, :interests
  end

  resources :individuals do
    resources :alerts, only: [:new, :create, :index]
  end

     resources :opportunities do
    resources :applications, only: [:new, :create]
    resources :individuals, only: [:index]
    end 

  resources :users, :individuals, :organisations, :opportunities, :posters, 
  :searches, :applications, :alerts

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'cookie_policy' => 'static_pages#cookie_policy'
  get 'register' => 'static_pages#register'
  get 'individual_faq' => 'static_pages#individual_faq'
  get 'organization_faq' => 'static_pages#organization_faq'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'admin'   => 'static_pages#dashboard'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  root 'static_pages#home'

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end

  def individual_faq
  end

  def organization_faq
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title, "About Community Impact Bucks") %>
<div class="about">
<p class="first-para">VolunteeringBucks is a service provided by Community Impact Bucks, the Volunteer Centre for Buckinghamshire.  It is a web portal where charities can advertise their volunteering opportunities and people can look for and apply for roles that interest them.</p>
<br/>
<p>For more information about Volunteering, please see our <%= link_to 'Individual FAQs', individual_faq_path, class: "red" %> or <%= link_to 'Organisation FAQs', organization_faq_path, class: "red" %></p>
<br/>
<p><b>For more information about Community Impact Bucks and our services please see our main website <%= link_to 'www.communityimpactbucks.org.uk', "http://www.communityimpactbucks.org.uk", target: "_blank", class: "red"  %></b></p>
</div>

app/views/static_pages/cookie_policy.html.erb
<% provide(:title, "Cookie Policy") %>

app/views/static_pages/dashboard.html.erb
<h2 class="form-header">Admin Dashboard</h2>

<div class="row">
<div class="col-md-3 col-md-offset-1">
<h4 class="subheading">Manage Data</h4>
<hr>

<%= link_to "Skills", admin_skills_path, class: "btn btn-primary form-button form-control" %>
<%= link_to "Interests", admin_interests_path, class: "btn btn-primary form-button form-control" %>
</div>
</div>
<br/>
<br/>
<br/>
<br/>

app/views/static_pages/home.html.erb
<% provide(:title, "Home") %>
<div class="row">
<div class="col-md-12 bigpic col-xs-12 col-sm-12">
<%= image_tag("dude.jpg", class: "main-img dude img-responsive") %>
</div>
</div>


<!-- Example row of columns -->
<div class="row two-buttons">
  <div class="col-xs-12 col-sm-12 col-md-5 col-md-offset-1">
  <%= link_to new_search_path do %>
    <button type="button" class="bouton left">I Want To <br>Volunteer</button>
  <% end %>
  </div>
  <div class="col-xs-12 col-sm-12 col-md-5">
  <%= link_to new_opportunity_path do %>
    <button type="button" class="bouton right">Post an <br>Opportunity</button>
  <% end %>
  </div>
</div><!-- end 2 buttons -->

app/views/static_pages/organization_faq.html.erb
<% provide(:title, "FAQ") %>