config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'interests/new'
  end

  namespace :admin do
  get 'interests/edit'
  end

  namespace :admin do
  get 'interests/index'
  end

  get 'sessions/new'

   namespace :admin do
    resources :users, :individuals, :organisations, :opportunities, :applications,
    :posters, :searches, :applications, :skills, :classifications, :districts, :interests
  end

  resources :individuals do
    resources :alerts, only: [:new, :create, :index]
  end

     resources :opportunities do
    resources :applications, only: [:new, :create]
    resources :individuals, only: [:index]
    end 

  resources :users, :individuals, :organisations, :opportunities, :posters, 
  :searches, :applications, :alerts

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'cookie_policy' => 'static_pages#cookie_policy'
  get 'register' => 'static_pages#register'
  get 'individual_faq' => 'static_pages#individual_faq'
  get 'organization_faq' => 'static_pages#organization_faq'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'admin'   => 'static_pages#dashboard'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  root 'static_pages#home'

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :individual
  has_and_belongs_to_many :skills
  has_and_belongs_to_many :interests

#  validate :validate_postcode

  def validate_postcode
    return unless self.postcode.nil?
    a = Postcodes::IO.new
    b = a.lookup(postcode) 
    if b.nil?
      return errors.add(:postcode, "#{postcode.upcase} is not a valid postcode.") 
    else
      self.postcode = b.postcode
      self.lat = b.latitude
      self.lng = b.longitude
    end
  end
end

app/controllers/alerts_controller.rb
class AlertsController < ApplicationController

  def new
    individual = current_user.individual
    @alert = individual.alerts.build
    @skills = Skill.all
    @interests = Interest.all
  end

  def create
    individual = current_user.individual
    @alert = individual.alerts.build(alert_params)
    if @alert.save
      redirect_to individual_alerts_path(individual)
    else
      render 'new'
    end
  end

  def index
    @alerts = current_user.individual.alerts.all
  end

   def edit
    @alert = Alert.find(params[:id])
    @skills = Skill.all
    @interests = Interest.all
  end

  def update
    @alert = Alert.find(params[:id])
    if @alert.update_attributes(alert_params)
      redirect_to individual_alerts_path(current_user)
    else
      render :edit
    end
  end

  def destroy
    @alert = Alert.find(params[:id]).destroy
    redirect_to individual_alerts_path(current_user)
  end

  private

  def alert_params
    params.require(:alert).permit(:name, :postcode, :distance, :under_18, :group, 
                            :expert, :search_id, :skill_ids => [], :interest_ids => [])
  end
end

app/helpers/alerts_helper.rb
module AlertsHelper
end

app/views/alerts/edit.html.erb
<% provide(:title, "New Role Alert") %>
<h2 class="form-header">Create a New Role Alert</h2>

<div class="row full-form">
  <div class="col-md-12">
    <%= form_for(@alert, html: { class: 'form-horizontal' }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="row">
      <div class="col-md-8 col-md-offset-2">

        <h4 class="subheading">Search Details</h4>
        <hr>

        <div class="form-group">
          <%= f.label :name, "* Role Alert Name", class: "col-md-4 control-label" %>
          <div class="col-md-6">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :postcode, "Search by location", class: "col-md-4 control-label" %>
          <div class="col-md-6">
          <%= f.text_field :postcode, class: "form-control", placeholder: "Please enter a postcode" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :distance, "Within how many km?", class: "col-md-4 control-label" %>
          <div class="col-md-6">
          <%= f.select :distance, [['within 5 km', 5], ['within 10 km', 10], ['within 15 km', 15], ['within 20 km', 20]], {prompt: "select distance"}, {class: "form-control"} %>
        </div>
        </div>

        <div class="form-group">
          <%= f.label :skill_ids, "Skills", class: "col-md-4 control-label" %>
          <div class="col-md-6">
          <%= f.collection_select :skill_ids, @skills, :id, :name, {prompt: "---"}, {multiple: true, class: "form-control"}   %>
        </div>
        </div>

        <div class="form-group">
          <%= f.label :interest_ids, "Interests", class: "col-md-4 control-label" %>
          <div class="col-md-6">
          <%= f.collection_select :interest_ids, @interests, :id, :name, {prompt: "---"}, {multiple: true, class: "form-control"}   %>
        </div>
        </div>

        <div class="form-group">
          <label class="control-label col-md-4">Suitable for:</label>
          <div class="col-md-6">

          <div class="checkbox">
            <%= f.label :under_18 do %>
            <%= f.check_box :under_18 %>
            <span>Under 18s?</span>
            <% end %>
          </div>

          <div class="checkbox">
            <%= f.label :group do %>
            <%= f.check_box :group %>
            <span>Groups?</span>
            <% end %>
          </div>

          <div class="checkbox">
            <%= f.label :expert do %>
            <%= f.check_box :expert %>
            <span>Expert?</span>
            <% end %>
          </div>
          </div>
        </div> <!-- /.form-group -->

        <div class="row">
          <div class="col-md-4 col-md-offset-4 col-xs-4 col-xs-offset-4 col-sm-4 col-sm-offset-4">
            <div class="form-group">
              <%= f.submit "Update Alert", class: "btn btn-primary form-button form-control" %>
            </div>
          </div>
        </div>

      </div>
    </div>
    <% end %>
  </div>
</div>

app/views/alerts/index.html.erb
<% provide(:title, "My Role Alerts") %>

<h2 class="form-header"><%= current_user.first_name %>'s Role Alerts</h2>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <p class="center">Create role alerts to retrieve saved searches and receive emails with the latest opportunities matching your search criteria.</p>
  </div>
  </div>
  <div class="row">
  <div class="col-md-2 col-md-offset-5">
    <%= link_to "Create Role Alert", new_individual_alert_path(current_user), class: "btn btn-primary form-button form-control" %>
  </div>
</div>
<br/>
<br/>



<h4 class="subheading">Current Role Alerts</h4>
<br/>
<div class="table-responsive">
  <table class="table table-bordered table-striped" id="sortable">
    <thead>
      <tr>
        <th>
          Name
        </th>
        <th>
          Location
        </th>
        <th>
          Skills
        </th>
        <th>
          Interests
        </th>
        <th>
          Suitable For
        </th>
        <th>
          Actions
        </th>
      </tr>
    </thead>
    <tbody>
      <% @alerts.each do |a| %>
      <tr data-item-id=<%= "sdfsf" %> class="item">
        <td>
          <%= a.name %>
        </td>
        <td>
          <% if a.distance %>
          <%= "Within #{a.distance} km of #{a.postcode}" %>
          <% end %>
        </td>
        <td>
          <% unless a.skills.empty? %>
          <% a.skills.each do |s| %>
          <li><%= s.name %></li>
          <% end %>
          <% end %>
        </td>
        <td>
          <% unless a.interests.empty? %>
          <% a.interests.each do |i| %>
          <li><%= i.name %></li>
          <% end %>
          <% end %>
        </td>
        <td>
          <% unless a.under_18 || a.group || a.expert %>
          <li>Anyone</li>
          <% end %>
          <% if a.under_18 %>
          <li>Under 18s</li>
          <% end %>
          <% if a.group %>
          <li>Groups</li>
          <% end %>
          <% if a.expert %>
          <li>Experts</li>
          <% end %>
        </td>
        <td>
          <%= link_to "Update", edit_alert_path(a), class: "red" %><br/>
          <%= link_to "Delete", a, method: :delete, data: { confirm: "Are you sure you want to delete this role alert?" }, class: "red" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>

<br/>
<br/>

app/views/alerts/new.html.erb
<% provide(:title, "New Role Alert") %>
<h2 class="form-header">Create a New Role Alert</h2>

<div class="row full-form">
  <div class="col-md-12">
    <%= form_for(@alert, html: { class: 'form-horizontal' }) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="row">
      <div class="col-md-8 col-md-offset-2">

        <h4 class="subheading">Search Details</h4>
        <hr>

        <div class="form-group">
          <%= f.label :name, "* Role Alert Name", class: "col-md-4 control-label" %>
          <div class="col-md-6">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :postcode, "Search by location", class: "col-md-4 control-label" %>
          <div class="col-md-6">
          <%= f.text_field :postcode, class: "form-control", placeholder: "Please enter a postcode" %>
          </div>
        </div>

        <div class="form-group">
          <%= f.label :distance, "Within how many km?", class: "col-md-4 control-label" %>
          <div class="col-md-6">
          <%= f.select :distance, [['within 5 km', 5], ['within 10 km', 10], ['within 15 km', 15], ['within 20 km', 20]], {prompt: "select distance"}, {class: "form-control"} %>
        </div>
        </div>

        <div class="form-group">
          <%= f.label :skill_ids, "Skills", class: "col-md-4 control-label" %>
          <div class="col-md-6">
          <%= f.collection_select :skill_ids, @skills, :id, :name, {prompt: "---"}, {multiple: true, class: "form-control"}   %>
        </div>
        </div>

        <div class="form-group">
          <%= f.label :interest_ids, "Interests", class: "col-md-4 control-label" %>
          <div class="col-md-6">
          <%= f.collection_select :interest_ids, @interests, :id, :name, {prompt: "---"}, {multiple: true, class: "form-control"}   %>
        </div>
        </div>

       <div class="form-group">
          <label class="control-label col-md-4">Suitable for:</label>
          <div class="col-md-6">

          <div class="checkbox">
            <%= f.label :under_18 do %>
            <%= f.check_box :under_18 %>
            <span>Under 18s?</span>
            <% end %>
          </div>

          <div class="checkbox">
            <%= f.label :group do %>
            <%= f.check_box :group %>
            <span>Groups?</span>
            <% end %>
          </div>

          <div class="checkbox">
            <%= f.label :expert do %>
            <%= f.check_box :expert %>
            <span>Expert?</span>
            <% end %>
          </div>
          </div>
        </div> <!-- /.form-group -->

        <div class="row">
          <div class="col-md-4 col-md-offset-4 col-xs-4 col-xs-offset-4 col-sm-4 col-sm-offset-4">
            <div class="form-group">
              <%= f.submit "Create Alert", class: "btn btn-primary form-button form-control" %>
            </div>
          </div>
        </div>

      </div>
    </div>
    <% end %>
  </div>
</div>