config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'interests/new'
  end

  namespace :admin do
  get 'interests/edit'
  end

  namespace :admin do
  get 'interests/index'
  end

  get 'sessions/new'

   namespace :admin do
    resources :users, :individuals, :organisations, :opportunities, :applications,
    :posters, :searches, :applications, :skills, :classifications, :districts, :interests
  end

  resources :individuals do
    resources :alerts, only: [:new, :create, :index]
  end

     resources :opportunities do
    resources :applications, only: [:new, :create]
    resources :individuals, only: [:index]
    end 

  resources :users, :individuals, :organisations, :opportunities, :posters, 
  :searches, :applications, :alerts

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'cookie_policy' => 'static_pages#cookie_policy'
  get 'register' => 'static_pages#register'
  get 'individual_faq' => 'static_pages#individual_faq'
  get 'organization_faq' => 'static_pages#organization_faq'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'admin'   => 'static_pages#dashboard'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  root 'static_pages#home'

end

app/models/interest.rb
class Interest < ActiveRecord::Base

  before_save :upcase_name

  has_and_belongs_to_many :organisations
  has_and_belongs_to_many :searches
  has_and_belongs_to_many :alerts

  validates :name, presence: true

  default_scope { order(:name) } 

  private
    def upcase_name
      self.name = name.downcase.capitalize
    end
end

app/controllers/admin/interests_controller.rb
class Admin::InterestsController < ApplicationController
   def index
    @interests = Interest.all
  end

  def new
    @interest = Interest.new
  end

  def create
    @interest = Interest.new(interest_params)
    if @interest.save
      flash[:info] = "#{@interest.name} has been successfully created."
      redirect_to admin_interests_path
    else
      render new_admin_Interest_path
    end
  end

  def edit
    @interest = Interest.find(params[:id])
  end

  def update
     @interest = Interest.find(params[:id])
    if @interest.update_attributes(interest_params)
      flash[:success] = "Interest updated successfully."
      redirect_to admin_interests_path
    else
      render new_admin_Interest_path
    end
  end

    def destroy
    @interest = Interest.find(params[:id]).destroy
    redirect_to admin_interests_path
  end

  private
  def interest_params
      params.require(:interest).permit(:name)
    end
end

app/helpers/admin/interests_helper.rb
module Admin::InterestsHelper
end

app/views/admin/interests/edit.html.erb
<% provide(:title, "Edit Skill") %>
<h2 class="form-header">Edit <%= @interest.name %></h2>

<div class="row full-form">
  <div class="col-md-12">
    <%= form_for([:admin, @interest], html: { class: 'form-horizontal' }) do |f| %>

    <div class="row">
      <div class="col-md-8 col-md-offset-2">

        <div class="form-group">
          <%= f.label :name, "* Interest Name", class: "col-md-4 control-label" %>
          <div class="col-md-6">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
      </div>
    </div> <!-- /.form-group -->

    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-xs-4 col-xs-offset-4 col-sm-4 col-sm-offset-4">
        <div class="form-group">
          <%= f.submit "Update Interest", class: "btn btn-primary form-button form-control" %>
        </div>
      </div>
    </div>

  <% end %>
  </div>
</div>

app/views/admin/interests/index.html.erb
<% provide(:title, "Manage Skills") %>

<h2 class="form-header">Manage Interests</h2>
<div class="row">
<div class="col-md-6 col-md-offset-3">
<div><%= link_to "Add New Interest", new_admin_interest_path, class: "btn btn-sm view-button" %>
<br/>
<br/>
</div>
<div class="table-responsive">
  <table class="table table-bordered table-striped" id="sortable">
    <thead>
      <tr>
        <th>
          Name
        </th>
        <th>
          Update
        </th>
        <th>
          Delete
        </th>
      </tr>
    </thead>
    <tbody>
      <% @interests.each do |s| %>
      <tr data-item-id=<%= "sdfsf" %> class="item">
        <td>
          <%= s.name %>
        </td>
        <td>
          <%= link_to "Update", edit_admin_interest_path(s), class: "red" %>
          </td>
          <td>
          <%= link_to "Delete", admin_interest_path(s), method: :delete, data: { confirm: "Are you sure you want to delete this interest?" }, class: "red" %>
        </td>
      </tr>
      <% end %>
    </tbody>
  </table>
</div>
</div>
</div>
<br/>
<br/>

app/views/admin/interests/new.html.erb
<% provide(:title, "New Interest") %>
<h2 class="form-header">Create a New Interest</h2>

<div class="row full-form">
  <div class="col-md-12">
    <%= form_for([:admin, @interest], html: { class: 'form-horizontal' }) do |f| %>

    <div class="row">
      <div class="col-md-8 col-md-offset-2">

        <div class="form-group">
          <%= f.label :name, "* Interest Name", class: "col-md-4 control-label" %>
          <div class="col-md-6">
            <%= f.text_field :name, class: "form-control" %>
          </div>
        </div>
      </div>
    </div> <!-- /.form-group -->

    <div class="row">
      <div class="col-md-4 col-md-offset-4 col-xs-4 col-xs-offset-4 col-sm-4 col-sm-offset-4">
        <div class="form-group">
          <%= f.submit "Create Interest", class: "btn btn-primary form-button form-control" %>
        </div>
      </div>
    </div>

  <% end %>
  </div>
</div>