config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
  get 'interests/new'
  end

  namespace :admin do
  get 'interests/edit'
  end

  namespace :admin do
  get 'interests/index'
  end

  get 'sessions/new'

   namespace :admin do
    resources :users, :individuals, :organisations, :opportunities, :applications,
    :posters, :searches, :applications, :skills, :classifications, :districts, :interests
  end

  resources :individuals do
    resources :alerts, only: [:new, :create, :index]
  end

     resources :opportunities do
    resources :applications, only: [:new, :create]
    resources :individuals, only: [:index]
    end 

  resources :users, :individuals, :organisations, :opportunities, :posters, 
  :searches, :applications, :alerts

  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'
  get 'cookie_policy' => 'static_pages#cookie_policy'
  get 'register' => 'static_pages#register'
  get 'individual_faq' => 'static_pages#individual_faq'
  get 'organization_faq' => 'static_pages#organization_faq'
  get    'login'   => 'sessions#new'
  post   'login'   => 'sessions#create'
  delete 'logout'  => 'sessions#destroy'
  get    'admin'   => 'static_pages#dashboard'

  resources :account_activations, only: [:edit]
  resources :password_resets,     only: [:new, :create, :edit, :update]

  root 'static_pages#home'

end

app/models/alert.rb
class Alert < ActiveRecord::Base
  belongs_to :individual
  has_and_belongs_to_many :skills
  has_and_belongs_to_many :interests

#  validate :validate_postcode

  def validate_postcode
    return unless self.postcode.nil?
    a = Postcodes::IO.new
    b = a.lookup(postcode) 
    if b.nil?
      return errors.add(:postcode, "#{postcode.upcase} is not a valid postcode.") 
    else
      self.postcode = b.postcode
      self.lat = b.latitude
      self.lng = b.longitude
    end
  end
end

app/models/search.rb
class Search < ActiveRecord::Base
  has_and_belongs_to_many :skills
  has_and_belongs_to_many :interests
  belongs_to :user

  def opportunities
    o = Opportunity.all
    o = o.where(group: true) if group
    o = o.where(under_18: true) if under_18
    o = o.where(expert: true) if expert
    o = o.joins(:skills).where('skill_id in (?)', skill_ids) unless skill_ids.empty?
    o = o.joins(:interests).where('interest_id in (?)', interest_ids) unless interest_ids.empty?
    o.uniq
  end

  # validate :validate_postcode

  def validate_postcode
    return unless self.postcode.nil?
    a = Postcodes::IO.new
    b = a.lookup(postcode) 
    if b.nil?
      return errors.add(:postcode, "#{postcode.upcase} is not a valid postcode.") 
    else
      self.postcode = b.postcode
      self.lat = b.latitude
      self.lng = b.longitude
    end
  end
 
end

app/controllers/searches_controller.rb
class SearchesController < ApplicationController
  def new
    @search = Search.new
    @skills = Skill.all
    @interests = Interest.all
    @opportunities = Opportunity.all
  end

 def create
    @search = Search.new(search_params)
    if @search.save
      redirect_to edit_search_path(@search)
    else
      render :new
    end
  end

  def edit
    @skills = Skill.all
    @interests = Interest.all
    @search = Search.find(params[:id])
  end

  def update
    @search = Search.find(params[:id])
    if @search.update_attributes(search_params)
      redirect_to edit_search_path(@search)
    else
      render :edit
    end
  end

  def search_params
      params.require(:search).permit(:name, :postcode, :last_name, :under_18,
                                   :distance, :expert, :group, :skill_ids => [], :interest_ids => [])
    end
end

app/helpers/searches_helper.rb
module SearchesHelper
end

app/views/searches/_opportunity.html.erb
<%= javascript_include_tag "location.js" %>
<hr>
  <% @opportunities.each do |o| %>
<div class="row newline">
  <div class="col-md-6 col-xs-6 col-sm-6 search-pane-left">
    <h4 class="search-title">
      <%= link_to o.name, opportunity_path(o), class: "search-title" %>
    </h4>
    <h5 class="search-title">
      <%= link_to o.organisation.name, organisation_path(o.organisation), class: "search-title" %>
    </h5>
    <p><span class="glyphicon glyphicon-map-marker"></span> <%= o.town %>&nbsp;<%= o.postcode %></p>
  </div>

  <div class="col-md-6 col-xs-6 col-sm-6 search-pane-right">
    <p>
      <span class="glyphicon glyphicon-time"></span> 
      Posted <%= time_ago_in_words(o.created_at) %> ago
    </p>
    <%= link_to "View", opportunity_path(o), class: "btn btn-sm view-button" %>
  </div>


  </div>
  <div id="map-base" class="testing"></div>
  
  <hr>
  <% end %>

app/views/searches/_results.html.erb
<hr>

<% if @search.opportunities.empty? %>
<p>Your search returned no results.</p>

<% else %>
<% @search.opportunities.each do |o| %>

<div class="row">
  <div class="col-md-6 col-xs-6 col-sm-6 search-pane-left">
    <h4 class="search-title">
      <%= link_to o.name, opportunity_path(o), class: "search-title" %>
    </h4>
    <h5 class="search-title">
      <%= link_to o.organisation.name, organisation_path(o.organisation), class: "search-title" %>
    </h5>
    <p><span class="glyphicon glyphicon-map-marker"></span> <%= o.town %>&nbsp;<%= o.postcode %></p>
  </div>

  <div class="col-md-6 col-xs-6 col-sm-6 search-pane-right">
    <p>
      <span class="glyphicon glyphicon-time"></span> 
      Posted <%= time_ago_in_words(o.created_at) %> ago
    </p>
    <%= link_to "View", opportunity_path(o), class: "btn btn-sm view-button" %>
  </div>
</div>
<p id="map"></p>

<hr>
<% end %>
<% end %>

app/views/searches/_search_form.html.erb
<hr>
<div class="row full-form">
  <div class="col-md-10 col-md-offset-1">
    <%= form_for(@search) do |f| %>
    <%= render 'shared/error_messages', object: f.object %>

    <div class="form-group">
      <%= f.label :postcode, "Search by location", class: "control-label" %>
      <%= f.text_field :postcode, class: "form-control", placeholder: "Please enter a postcode" %>
      </div>

  <div class="form-group">
  <%= f.label :distance, "Within how many km?", class: "control-label" %>
      <%= f.select :distance, [['within 5 km', 5], ['within 10 km', 10], ['within 15 km', 15], ['within 20 km', 20]], {prompt: "select distance"}, {class: "form-control"} %>
      </div>
    <hr>

    <div class="form-group">
      <%= f.label :skill_ids, "Skills", class: "control-label" %>
      <%= f.collection_select :skill_ids, @skills, :id, :name, {prompt: "---"}, {multiple: true, class: "form-control"}   %>
    </div>
    <hr>

    <div class="form-group">
      <%= f.label :interest_ids, "Interests", class: "control-label" %>
      <%= f.collection_select :interest_ids, @interests, :id, :name, {prompt: "---"}, {multiple: true, class: "form-control"}   %>
    </div>
    <hr>

    <div class="form-group">
      <div>Suitable for:</div>
      <div class="checkbox">
        <%= f.label :under_18 do %>
        <%= f.check_box :under_18 %>
        <span>Under 18s?</span>
        <% end %>
        </div>

      <div class="checkbox">
        <%= f.label :group do %>
        <%= f.check_box :group %>
        <span>Groups?</span>
        <% end %>
      </div>

      <div class="checkbox">
        <%= f.label :expert do %>
        <%= f.check_box :expert %>
        <span>Expert?</span>
        <% end %>
      </div>
    </div> <!-- /.form-group -->

<div class="row">
  <div class="col-md-4 col-md-offset-4 col-xs-4 col-xs-offset-4 col-sm-4 col-sm-offset-4">
    <div class="form-group">
      <%= f.submit "Search", class: "btn btn-primary form-button form-control" %>
    </div>
    </div>
    </div>
    <% end %>
  </div>
</div>

app/views/searches/edit.html.erb
<% provide(:title, "Search Opportunities") %>
<h2 class="form-header">Search Available Opportunities</h2>
<div class="row">
  <div class="col-md-8">
  <h3 class="form-header2">Search Results</h3>
    <%= render 'searches/results' %>
  </div>
  <div class="col-md-4">
  <h3 class="form-header2">Search Filters</h3>
    <%= render 'searches/search_form' %>
  </div>
</div>

app/views/searches/new.html.erb
<% provide(:title, "Search Opportunities") %>
<h2 class="form-header">Search Available Opportunities</h2>
<div class="row">
  <div class="col-md-8">
  <h3 class="form-header2">Current Opportunities</h3>
    <%= render 'searches/opportunity' %>
  </div>
  <div class="col-md-4">
  <h3 class="form-header2">Search Filters</h3>
    <%= render 'searches/search_form' %>
  </div>
</div>

app/views/searches/show.html.erb
<% if @search.opportunities.empty? %>
<p>Your search returned no results.</p>
<% else %>
<% @search.opportunities.each do |o| %>
<p><%= o.name %></p>
<% end %>
<% end %>